### ISSUE TITLE
适配 qqguild

### ISSUE THREAD

**Issue by KomoriDev** [bridgeL/ayaka#3]
是否考虑适配 [qqguild](https://github.com/nonebot/adapter-qqguild) ？

**Comment by bridgeL** [comment]
没号测试，内测资格不给我

**Comment by KomoriDev** [comment]
可以考虑用 [频道补丁](https://github.com/mnixry/nonebot-plugin-guild-patch) 来进行适配，虽然不是官方的，但是很方便。（如果没打算适配频道的话可忽略）

**Comment by bridgeL** [comment]
感谢，我晚些时候研究下源码

**Comment by bridgeL** [comment]
摸了

**Comment by KomoriDev** [comment]
酱紫就能适配频道，但是它只是补丁并不是适配器。官方的机器人我注册俩，可以用官方的api，想要的话可以借
（主要是我自己做不出来（悲），但这游戏真心觉得好玩）
```py
from nonebot.plugin import on_command
from nonebot.adapters.onebot.v11 import Bot, MessageEvent, MessageSegment

from nonebot_plugin_guild_patch import GuildMessageEvent

matcher = on_command('image')

@matcher.handle()
async def _(bot: Bot, event: MessageEvent | GuildMessageEvent):
    await matcher.send(
        MessageSegment.image(
            file='https://1mg.obfs.dev/',
            cache=False,
        ))
```

**Comment by bridgeL** [comment]
gocq目前不支持私信，这会让ayaka的一些功能无法使用，尤其对于卡牌游戏，这是致命的。等待gocq私信支持中...

**Comment by bridgeL** [comment]
0.0.3.0版本将部分解决ayaka对qqguild的适配问题，但仍无法发送私信

**Comment by KomoriDev** [comment]
是否可以增加绑定QQ功能，将两种id绑定一起，然后在QQ而非QQ频道中发送私信（像犯人在跳舞这种游戏也本来就是要加bot好友的）

**Comment by bridgeL** [comment]
好主意！我这两天尝试一下

**Comment by bridgeL** [comment]
绑定qq功能目前仅在犯人在跳舞中实现，ayaka暂不添加此功能

**Comment by KomoriDev** [comment]
收到，谢谢作者，这就尝鲜🎉
